### ISSUE TITLE
following your readme

### ISSUE THREAD

**Issue by natesire** [HiImJayHireMe/rocinante#1]
Interesting repo. Are there other setup items I need to do? I pasted the lines 1 by 1.

/dev/fd/63: line 1: clj: command not found
/dev/fd/63: line 2: cd: some.example: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'build'.  Stop.
gio: file:///home/colombia/rocinante/resources/public/index.html: Error when getting information for file “/home/colombia/rocinante/resources/public/index.html”: No such file or directory
Couldn't get a file descriptor referring to the console

**Comment by jjtolton** [comment]
Hi there!  Sorry just saw this.  You need to have the prerequisites installed! 
Make sure Clojure is installed: https://clojure.org/guides/getting_started
Make sure npm and yarn are installed: https://www.npmjs.com/get-npm
https://classic.yarnpkg.com/en/docs/install

Then try it again!

**Comment by jjtolton** [comment]
Closing for now.  Please let me know if there's anything else I can do to help!
